### ISSUE TITLE
이메일 주소 입력시 스페이스 입력되는 오류 발생 

### ISSUE THREAD

**Issue by donggi12** [finset-io/better-qa#118]
- 화면 위치 
회원가입 

- As-is
메일주소 복사 후 베러 이메일 입력 필드에 붙여넣는 경우, 스페이스(띄어쓰기)가 입력됨 

- To-be
스페이스가 들어와도 문자열이 맞으면 입력받도록 수정 필요.

**Comment by EtErNaLiFe12** [comment]
기획팀과 검토 후 스페이스 자체를 입력이 안되게끔 변경되었습니다. production에 반영된 내용 입니다.
