### ISSUE TITLE
연결 자산 중, 금융투자 계좌(키움) 하나 누락됨

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#119]
- 화면 위치
: 자산 홈

- As is
: 연결 자산 중, 금융투자 계좌(키움) 하나 누락됨. 

- To be
: 연결 자산 - 정상 유지되도록 해야 함. 

- 케이스 **(옥프로님)**

**Comment by donggi12** [comment]
- dev comment 
현재 DB에서 조회해보니, 키움증권 내에 보유하고 있는 총 3개의 계좌 중에 말씀주신 1개의 계좌만 IS_CONSENT (전송요구 여부)  항목이 FALSE로 바뀌어 있어서 누락된 것으로 확인됩니다. 이 부분은 원인을 확인해보겠습니다. @Paul-scpark

**Comment by doidoit** [comment]
**(옥프로님)**
**지금은 문제되던 특정 계좌 잘 보이나,** 

수시로 보였다 안 보였다 함. 
(통계적으로 보면) 주로 주말에 특정계좌 안 보임. 

**같은 현상 나오면 QA 올릴 예정**
