### ISSUE TITLE
부동산 삭제 UI 반영 느림

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#121]
1 화면 위치
: 자산탭 > 실물 자산 - 내 부동산 연결하기 - 연결 해제(부동산 삭제)

2 증상
: 아이폰 - 부동산 연결 해제 시, 바로 반영 안 됨. 
  종료 후 재실행하면 반영 됨.
  (안드로이드는 정상 반영됨)

3 개선
: 부동산 연결 해제 시, 바로 반영되도록 해야 함. 

4 케이스 1 **(영수프로님)**
- OS/디바이스명: iOS / 아이폰 12 미니 
- 앱 버전: 1.0.13

5 영상 첨부 (comment에 첨부)

**Comment by doidoit** [comment]
https://user-images.githubusercontent.com/98443099/180901289-73f1e70a-fff7-4c11-b6ee-e7e8b3418365.MP4

**Comment by EtErNaLiFe12** [comment]
p2에 부동산 삭제 관련 QA등록되어있고 중복 내용입니다. complete으로 전환 해놓겠습니다. closed부탁드립니다 @doidoit
