### ISSUE TITLE
카드 사용 금액 - 몇 초 차이로 금액 다르게 불러오는 이슈

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#134]
1. 화면 위치
: 자산 홈 - 소비 탭 - 0월 카드 사용금액

2. 증상
: 0월 카드 사용금액 - 몇 초차이로 금액 다르게 불러옴

3. 개선
: 카드 사용금액 수치 일관성 있게 해야 함. 

4. 케이스 1 **(구프로님)**
(1)
![Image](https://user-images.githubusercontent.com/98443099/181164120-be9e7873-1026-4b60-a95c-e8fa03cf15dd.png)
(2)
![Image](https://user-images.githubusercontent.com/98443099/181164119-345f6f8a-5dec-4cd3-a5a6-35fad770b03e.png)

**Comment by cakeycarrot** [comment]
앱 데이터 새로 불러오는 경우 카드정보데이터가 업데이트 되면서 금액이 달라보일 수 있습니다.
