### ISSUE TITLE
초기 진단 진입 시, 점수 없는 상태로 노출되는 이슈 (연결 전인 것처럼 노출됨)

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#142]
1. 화면 위치
: 자산 탭 > 진단 탭 초기 진입 시

2. 증상
: 초기 진단 진입 시, 점수 없는 상태로(연결 전인 것처럼) 화면 노출됨. 
  (기존에는 정상 노출됐음)

3. 개선
: 이전에 접속 기록이 있으면, 
  진단 데이터가 캐싱돼서 기존 진단 점수가 그대로 있어야 함. 

4. 케이스 1 **(구프로님)**

OS/디바이스명: iOS / 아이폰 12 미니
앱 버전: 1.0.13

https://user-images.githubusercontent.com/98443099/181401526-22cc5d59-0acc-4728-ac36-67099a424ec4.MP4

**Comment by kooyongseok-finset** [comment]
수정 및 반영완료
