### ISSUE TITLE
자산연결 - 네이버 인증서 연결 과정 중 - 약관 동의 후, 흰 화면 뜨고 응답 없음

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#144]
1. 화면 위치
: 자산연결 - 네이버 인증서 연결 과정 중

2. 증상
: 네이버 인증서 연결 과정 중 - 약관 동의 후, 흰 화면 뜨고 응답 없음

3. 개선
: 네이버 인증서 정상 연결돼야 함. 

4. 케이스1 **(한프로님)**

(comment에 영상 첨부)

5. Dev comment

![Image](https://user-images.githubusercontent.com/98443099/181404806-efc64a7a-f1dc-4010-8be9-18765d16f1a1.png)

![Image](https://user-images.githubusercontent.com/98443099/181404844-4077a423-8ae4-4243-a202-a24160b91a32.png)

**Comment by doidoit** [comment]
https://user-images.githubusercontent.com/98443099/181406276-2d0d4487-fd7e-4aaa-915f-1799b22bfa4b.mp4

**Comment by bobur-finset** [comment]
Naver 미가입자 자산연결시 안내 메시지 필요함
``` 
Aug 22 04:08:16 prd-etc1 main-prd-etc1.1[13778]: [2022-08-22 04:08:16.058] #033[31mERROR#033[39m: #033[36mBaseHttpService - =======[post] response error========== log={"tx":"ZVAAIB0000MTPZFR040815989","type":"response","status":404,"path":"https://mydata.ekyc.naver.com//v1/ca/sign_request","data":{"rsp_code":"40403","rsp_msg":"user not found"},"rspTime":68,"apiCode":null,"orgCode":null,"txType":null}, params={"sign_tx_id":"ZVAAIB0000_ZYAAQH0000_20220822040815_000000001888","user_ci":"nEGCnl6IhyHbENZkMouzUnzbwpz4qvGxls42NDvYKZIGg17ywfSvRc4nJknolZY2LCqDfOc0TOw/MvwG3OMyyg==","request_title":"마이데이터전자서명","device_code":"MO","device_browser":"NA","return_app_scheme_url":"betterdayapp://private/naver/callback","consent_type":"1","consent_cnt":1,"consent_list":[{"consent_title":"상세정보 전송요구를 위한 가입상품목록 조회","consent":"49b19886ed7c76f9401c3e36b630e31b99e445f50ec5d88ea29d8213ba66d3cc","consent_len":269,"tx_id":"MD_ZVAAIB0000_A1AAEO0000_0000000000_ZYAAQH0000_20220822040815_000000001888"}]}#033[39m
```

**Comment by alexfinset** [comment]
Error Case:
- 사용자 휴대폰에 NAVER 앱이 설치되어있습니다.
- 사용자가 NAVER 계정이 없습니다.

오류 메시지를 표시하여  사용자에게 알려야 합니다.

**예: 네이버 앱에 로그인 해주시기 바랍니다.**

@kimpilwon

**Comment by alexfinset** [comment]
네이버 app 있는데 가입한적이 없는 경우
 - 네이버 App에서 계정을 찾지 못 하였습니다. 인증하려는 계정을 확인해주세요.
 
 다른 case들
 - 네이버 App에서 인증이 실패했습니다
