### ISSUE TITLE
실물자산 - 부동산 삭제 기능 안 됨

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#148]
1. 화면 위치
: 자산탭 - 실물자산 - 부동산 삭제 

2. 증상
: 부동산 삭제 기능 안 됨 
  (부동산을 삭제하시겠어요? 삭제 시 복구할 수 없어요 - 삭제) 클릭하면
  (삭제에 실패했습니다. 다시 시도해주세요.) 메세지 나옴. 

3. 개선
: (부동산 삭제) 정상 기능

4. 케이스1 **(구프로님 / 도이프로)**
(1) 구프로님 
OS/디바이스명: iOS / 아이폰 12 미니
앱 버전: 1.0.13

 iOS.13.MP4 

https://user-images.githubusercontent.com/98443099/181422222-ceafdef0-479b-41fc-a601-22cc4a8f4cac.MP4

(2) 도이프로
OS/디바이스명: Android / 갤럭시 s21
앱 버전: 1.0.15

https://user-images.githubusercontent.com/98443099/181422379-01ef93d4-c2e2-48b9-b687-3bed39bcf278.mp4

**Comment by GwonHyeok** [comment]
@cakeycarrot 삭제 API 콜하면 삭제 되는거로 확인되는데 테스트 부탁드립니다

**Comment by doidoit** [comment]
@GwonHyeok 

안녕하세요 에코님! 
개발완료 후 developed으로 status 변경만 해주시면, 
제가 개발계에서 확인 후에 closed 하겠습니다!
감사합니다=)

**Comment by GwonHyeok** [comment]
@doidoit 알겠습니다!
