### ISSUE TITLE
자산 홈 - (투자 현황) - (금융자산 - 투자)자산 있음에도 (내용 노출되지 않음)

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#156]
1. 화면 위치
: 자산 홈 - 투자 현황 

2. 증상
: (자산 홈 - 금융 자산 - 투자)에 자산 연결되어 있음에도 
  (자산 홈 - 투자 현황) 내용 노출되지 않음.  

3. 개선
; (자산 홈 - 투자 현황) 내용 정상 노출

4. 케이스1 **(영수프로님)**

https://user-images.githubusercontent.com/98443099/181716147-92e15ea2-9d21-4cd2-ad0c-c62abb44e406.mov

**Comment by ys-gitple** [comment]
현재 정상적으로 표시됩니다. 
@bobur-finset 혹시,공유하는 제 계정에서, KB증권 자산 연결 추가 한건가요?

**Comment by doidoit** [comment]
재현 안 됨 (케이스1 - 영수프로님)
-> closed
