### ISSUE TITLE
진단 결과 상세 - 투자 자산 관리 데이터 불러오지 못 함 (자산 정상 업데이트 상태)

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#161]
1. 화면 위치
: 진단 탭 > 결과 상세보기 > 종합 - 투자 자산 관리

2. 증상
: 자산 정상 업데이트 상태임에도
  (투자 자산 관리) 데이터 불러오지 못 함. 

3. 개선
: 투자 자산 관리 데이터 정상적으로 불러와야 함. 

4. 케이스 1 **(구프로님)**

https://user-images.githubusercontent.com/98443099/182107846-260b3f11-15e3-45c9-93f8-74eadaf55b2c.MP4

**Comment by kooyongseok-finset** [comment]
수정 및 반영완료
