### ISSUE TITLE
자산연결 후 - 자산 홈 - (자산조회 내역) / (자산 탭 그래프 수치) 이상 (같은 연결 상태에서 수치/그래프 모양 계속 변동 있음)

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#173]
1. 화면 위치
:  자산 홈 - 자산 조회 내역 / 자산 탭 그래프 수치

2. 증상
: (1) 키움증권-위탁종합 계좌1개 수치 이상 (자산 연결 상태/실제 계좌 변동 없는 상태에서)
       (투자 종목 있음에도 뜨지 않음. 입출금내역(배당금/이자)만 수치로 잡힘. 

 (2) 새로고침 후 나의 순자산/투자 현황 정상적으로 돌아왔는데
      그래프 모양/수치 정상으로 돌아오지 않음. 

3. 케이스2 **1) 도이프로 / 2) 조프로님(필요 시 추가 확인 예정)/ 3) 권프로님**

1) -1 키움증권 계좌 1개 수치 이상 (도이프로)
[**#119 (現 open 상태) (옥프로님) 연결 자산 중 키움증권 계좌 1개 누락되는 비슷한 이슈.**](https://github.com/finset-io/better-qa/issues/119)
[**#97 (現 open 상태)동일 QA (도이프로) - 키움증권 계좌 1개 수치 이상**
](https://github.com/finset-io/better-qa/issues/97)

(상) 정상 수치
![Image](https://user-images.githubusercontent.com/98443099/182793903-4029e7ac-c26d-4f57-9fe8-dd3ef2aa4b9e.jpg)

(하) 이상 수치 (투자 종목/해당 금액 누락)
![Image](https://user-images.githubusercontent.com/98443099/182793465-ba443539-cc4b-4927-8bf8-c896a2831b38.jpg)

2) - 2 새로고침 후 나의 순자산/투자 현황 수치 동일하게 이상함에도
         그래프 모양/수치는 다름 (도이프로)

(상) 정상 모양/수치
![Image](https://user-images.githubusercontent.com/98443099/182794763-a333a606-08c2-4da3-bf91-c2735d2fcc6a.png)

(중) 순자산/투자 현황 수치 이상 그래프 1 
![Image](https://user-images.githubusercontent.com/98443099/182795342-36e5d681-e85a-49fa-83ac-875df96f051f.png)

(하) 순자산/투자 현황 수치 이상 그래프 2
![Image](https://user-images.githubusercontent.com/98443099/182795755-40471b46-69d0-48f0-9733-b1f762608129.png)

(추가) 순자산/투자현황 (자산 연결 상태 / 수치) 정상임에도
           그래프 모양/수치 이상함 (순자산 그래프 수치가 범위 100원 ~ 300원으로 나옴)

(도이프로)
https://user-images.githubusercontent.com/98443099/183009643-e9ea91c6-718c-4bba-ae6a-30fe78b1ecd0.mp4

(권프로님)
![Image](https://user-images.githubusercontent.com/98443099/183018806-707f1c6a-70e3-448e-97e0-52a2d0f347d4.png)
![Image](https://user-images.githubusercontent.com/98443099/183018805-378d86d4-662a-4eaa-898f-0c3cb6cdc2cc.png)

**Comment by Paul-scpark** [comment]
https://github.com/finset-io/betterday/issues/1342
