### ISSUE TITLE
자산연결관리 - (만료예정)과 (만료) 리스트가 동일함

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#186]
1. 화면 위치
: 자산연결관리 - (만료예정)과 (만료)리스트

2. As is 
: 자산연결 (만료예정)과 (만료) 리스트가 동일함. 

3. To be
: 해당 이슈 정상인지 확인 필요

4. 케이스1 **영수프로님**

(1) 요약 이미지
![Image](https://user-images.githubusercontent.com/98443099/183589541-2bb34e89-9939-4c4e-94b0-cf9dc018bfe1.png)

(2) 첨부 영상
(comment에 추가)

**Comment by doidoit** [comment]
https://user-images.githubusercontent.com/98443099/183590067-4c775688-dd13-43a0-bf61-e16854180d47.MP4

**Comment by ys-gitple** [comment]
현재 버전 1.10.16 재현 안됨
