### ISSUE TITLE
FE-BE 금융자산 - 금액 수치가 전혀 맞지 않음

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#192]
1. 화면 위치
: 자산 탭 - 금융 자산 > 한국투자증권 위탁계좌 금액

2. As is
: 금융자산 금액 수치가 전혀 맞지 않음. 
  (첨부 이미지 참고 - 좌측 토스 금액이 정상 수치)

3. To be
: 금융자산 금액 수치 정상화

4. 케이스1 **구프로님**

![Image](https://user-images.githubusercontent.com/98443099/184096977-b79b42ec-9378-4928-b11e-90ab2c8ea475.png)

**Comment by kooyongseok-finset** [comment]
@bobur-finset 와 확인 결과 현재는 정상로드됨, 원인 확인해보기로 했습니다.
