### ISSUE TITLE
BE 1D: 자산 연결 오류 - 연결할 자산이 없습니다 / 소비 - 카드 조회 정상 기능하지만, 자산 탭 - 자산 확인 안 됨

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#199]
1. 화면 위치
: 자산 연결 시

2. 증상
: (1) **(도이프로)** 자산 연결 오류 - 연결할 자산을 선택하세요. - 연결성공 14건이 뜨고 - 확인을 누르면
      연결할 자산이 없습니다 화면으로 연결
      **타 케이스 정상 연결되는 것 확인**

  (2) **(조프로님)**
       자산 연결해서 소비 탭 - 카드 조회는 되는데, 
       자산 탭 - 자산 확인 안 됨.  
      **타 케이스 정상 연결되는 것 확인**

3. 개선
: 자산 연결 정상 기능

4. 케이스2 **도이프로 / 조프로님**

(영상 comment 첨부)
**(1) 도이프로**
![Image](https://user-images.githubusercontent.com/98443099/184854847-edd858b6-4217-4f78-97ee-4b372b7a6bc0.jpg)
![Image](https://user-images.githubusercontent.com/98443099/184854848-955d4d35-a0de-4478-ac5d-21cfa2babdff.jpg)

**(2) 조프로님**
https://user-images.githubusercontent.com/98443099/185275675-3a4b36a1-ea33-4c09-8af7-3077b03a214c.MP4

**Comment by doidoit** [comment]
https://user-images.githubusercontent.com/98443099/185014309-662db12f-dcca-45ae-8eb7-320d3330a1d2.mp4

**Comment by sjhanFinsetN** [comment]
NH증권에 자산이 있는데도 연결할 자산정보가 없다고 나옴 (얼마 전까지는 연결되었음)

![Image](https://user-images.githubusercontent.com/99164564/185025149-122325da-077c-4195-bcd2-b749f423c25d.png)

**Comment by kimpilwon** [comment]
자산 갱신에 관련된 종합적인 문제
1. 마이데이터 자산과 실물/가상자산 별도로 통신 GET ASSET ALL 분리필요.
2. 마이데이터 기관중에서도 실패한건 별도로 TRY CATCH 통신 완료된건 갱신 해줘야함.
3. 갱신이 안된 기관,업권,계좌가 있다면 ui 표시

**Comment by Paul-scpark** [comment]
현재 get asset all에서 마이데이터 및 부동산, 가상자산도 호출하고 있음.
그런데 추가적으로 부동산, 자동차, 가상자산 API도 호출하고 있고, 이 API들이 pending 되면서 get asset all도 delay 됨.

- [ ] BE: get asset all API와 개별 부동산, 자동차, 가상자산 API의 interface 통일시키기
- [ ] FE: get asset all API에서 받은 마이데이터 및 부동산, 자동차, 가상자산 데이터로 통합 관리하기
  - 부동산, 자동차, 가상자산 관련 개별 API는 삭제
