### ISSUE TITLE
카드 이벤트 관련 - 다른 탭 로딩 시 살짝 깜빡거리며 작아졌다 커짐

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#214]
1. 증상
: 다른 탭 로딩 시 살짝 깜빡거리며 레이아웃 작아졌다 커지는 것으로 보임

2. 영상 첨부
: **구프로님**

https://user-images.githubusercontent.com/98443099/185573193-cbc2281a-abf2-440d-b752-868437b829d1.mov

**Comment by kooyongseok-finset** [comment]
수정 및 반영 완료
