### ISSUE TITLE
카드 이벤트 관련 - 사업자 전용관 상품 - 모두보기에서 상품설명 첫 줄이 표기되지 않는 이슈

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#215]
1. 증상
: 사업자 전용관 상품 - 모두보기에서 상품설명 첫 줄이 표기되지 않는 이슈

2. 관련 사진 첨부
: 
![Image](https://user-images.githubusercontent.com/98443099/185573900-43b9b15a-343d-476f-869d-dc0d31d7bc44.jpg)

**Comment by kooyongseok-finset** [comment]
해결됨. 상품 등록 이슈였던 것으로 파악
