### ISSUE TITLE
카드 이벤트 관련 - 이전에 본 카드 정보가 잠깐 노출되는 이슈

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#216]
1. 증상
: 이전에 본 카드 정보가 잠깐 노출되는 이슈

2. 영상 첨부
: 
https://user-images.githubusercontent.com/98443099/185574360-b9c7c903-2a7f-447d-9aa5-e3e0b5f4f40f.MOV

**Comment by kooyongseok-finset** [comment]
수정 및 반영완료
