### ISSUE TITLE
PUSH 알림 오지 않음

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#40]
1 화면 위치
: 펀도라

2 증상
: android 및 IOS PUSH 알림 오지 않음

3 개선
: 펀도라 PUSH 알림 정상적으로 올 수 있도록 해야 함. 

4 케이스 1 **(초프로님)**
- OS / 디바이스명:  인성프로님 Z플립 3
- 앱 버전: 1.0.15

5 영상 첨부 
(1) push 알림 안 뜸. 
https://user-images.githubusercontent.com/98443099/180905758-ce0e6797-5e80-4b9f-b164-f877fea699ca.mp4

(2) 정상 push 알림 
https://user-images.githubusercontent.com/98443099/180906010-0cdb23b9-05dd-4488-8098-ab9718f2b13d.mp4

6 기획/디자인 comment
아래 정상작동 
(2. 신프로님 갤럭시 S20 FE 5G
3. 영수프로님 아이폰 12 미니 
4. 윤지프로님 아이폰 13 pro (15.5))

**Comment by alexfinset** [comment]
@doidoit 
각 사용자의 앱 version 확인부탁드립니다.

FCM 푸시 기능
iOS release v1.0.13
Android release v1.0.15

[참고하세요](https://finsetn.slack.com/archives/C02DHCHPJVA/p1658272972065279)

**Comment by alexfinset** [comment]
https://github.com/finset-io/betterday/issues/483

**Comment by doidoit** [comment]
@alexfinset 
넵 각 케이스 확인 후에 다시 comment 남기겠습니다!

**Comment by doidoit** [comment]
@alexfinset push 알림 정상 작동됩니다. 감사합니다!

**Comment by doidoit** [comment]
@alexfinset 
4가지 케이스 확인 후 
초프로님 케이스만 push가 안 떠서 
위에 내용 새로 업데이트했습니다!

ㅡ (아래는 업데이트 내용)

4 케이스 1 **(초프로님)**

OS / 디바이스명: 인성프로님 Z플립 3
앱 버전: 1.0.15

5 영상 첨부
(1) push 알림 안 뜸.
https://user-images.githubusercontent.com/98443099/180905758-ce0e6797-5e80-4b9f-b164-f877fea699ca.mp4

(2) 정상 push 알림
https://user-images.githubusercontent.com/98443099/180906010-0cdb23b9-05dd-4488-8098-ab9718f2b13d.mp4

**Comment by doidoit** [comment]
초프로님 케이스
> 로그인 후 바로 들어가서 push 알림 안 되는 것으로 예상
> 현재 push 알림 정상 기능하므로 closed 처리
