### ISSUE TITLE
거래소 연결 시, 시세 화면 미노출 오류

### ISSUE THREAD

**Issue by donggi12** [finset-io/better-qa#64]
- 화면위치 
베러 홈화면

- As-is
거래소 연결 상태에서 [홈화면] -[ 가상자산] 탭을 누르면 가상 자산 시세 를 볼 수 있는 것이 아닌 바로 [보유자산]으로 연결됨

- To-be
거래소 연결 상태에서 [홈화면] -[ 가상자산] 탭을 누르면 가상 자산 시세 를 볼 수 있는 화면(피그마 : MD1400_1_ 가상자산 연결 후)으로 이동 후, ‘내 가상자산 조회하기’ 클릭 시, [보유자산]으로 연결하도록 수정 필요.

- 영상첨부
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/104746013/179388853-f28fa800-a7b5-4d36-b8f8-0aa0496d0790.gif)

**Comment by cakeycarrot** [comment]
@kooyongseok-finset 자산하나라도 연결되어있으면 대시보드로 이동되게 지난 번에 요청있어서 수정한 부분인데요 확인 부탁드립니다~!

**Comment by kooyongseok-finset** [comment]
@cakeycarrot 네 그게 맞습니다.
해당 이슈 close 합니다. 
위 영상은 시세확인이라고 노출된 것을 보니 연결 전 상태 같네요.

연결 전 : 시세 조회
연결 후 : 내 가상자산 대시보드

위 동작이 맞습니다.
