### ISSUE TITLE
차량 두대 이상인 경우, 상세 정보 이동 오류

### ISSUE THREAD

**Issue by donggi12** [finset-io/better-qa#68]
- 화면위치 
실물자산 > 등록된 자동차 

- As-is
차량 두대 이상인 경우, 두번째 차량 눌러도 첫번째 차량으로 연결됨. 

- To-be
두번째 차량 누르면 두번째 차량 정보로 연결되도록 수정필요

- 영상 첨부
https://user-images.githubusercontent.com/98443099/180121191-a0478a6f-decf-4d4a-8f49-2139bea6be33.MP4

**Comment by kooyongseok-finset** [comment]
해결됨
