### ISSUE TITLE
추천코드 공유 시, 카카오톡 공유하기 연결되지 않음

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#82]
- 화면위치
: 전체탭 > 설정 - 나의추천코드 - 카카오톡 공유하기

- 증상
: 아이폰에서 카카오톡 공유하기 버튼 눌러도 카톡으로 연결되지 않음
(안드로이드에서는 정상 연결)

- 개선
: 아이폰 - 추천코드 - 카카오톡 공유하기 버튼
정상적으로 카톡 연결될 수 있도록 해야 함. 

![Image](https://user-images.githubusercontent.com/98443099/179688528-fb1fe633-8a98-4ed2-98a8-693c7d2140ef.png)

**Comment by donggi12** [comment]
better app version 관련 이슈 

최신 버전으로 진행시 해당 기능 정상 작동함. 

+ 현재 최신 버전 이용시, 다음 업데이트 발생 경우 강제 업데이트 알림창 활성화됨
