### ISSUE TITLE
내 자산 연결하기 - 추천기관 전체 선택 - 네이버 인증서 인증서 조회 실패

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#84]
- 화면 위치
: 자산탭 - 내 자산 연결하기 - 추천기관 전체 선택 체크

- As is
: 내 자산 연결하기 - 추천기관 전체 선택 시 
네이버 인증서 연결하면 인증서 조회가 실패됨.
다시 시도해도 실패. 

(연결이 됐다가 안됐다가 함. 
근데 연결이 안 되고 나서, 전체 선택에 해당하는 기관들을 
은행/카드/보험/투자 나눠서 연결하거나
적당히 쪼개서 연결해보면 정상 연결됨.)

- To be
: 네이버 인증서 연결이 정상적으로 돼야 함 

- 케이스 **(도이프로)**

https://user-images.githubusercontent.com/98443099/180104747-617cfba1-9879-411b-a962-b85a4c6b1313.mp4

![Image](https://user-images.githubusercontent.com/98443099/179873075-8237231f-0935-46a4-b812-cee5e9d98095.jpg)

**Comment by EtErNaLiFe12** [comment]
@doidoit  안녕하세요 JB프로 입니다. 네이버 앱 자체 혹시 업데이트가 안되어있다면 한번 업데이트 후에 시도 해보실 수 있을까요??

**Comment by doidoit** [comment]
@EtErNaLiFe12 안녕하세요! 

네이버 업데이트 후 다시 해봤는데요, 
이제는 (한번에 잘 연결될 때)가 있고 - [영상2] / 
(한번에 안 돼서 다시 하면 연결될 때 - [영상1])가 있습니다!

[영상1]
https://user-images.githubusercontent.com/98443099/180337355-a8cefcdb-e304-499d-92dd-2014b783e306.mp4

[영상2]

https://user-images.githubusercontent.com/98443099/180337469-7e999dce-6f1c-4734-a0ec-0fceb589c8dc.mp4

**Comment by doidoit** [comment]
재현 안 됨 (케이스1 - 도이프로) 
-> closed
