### ISSUE TITLE
자산 연결 중, 약관 동의 시 오류 발생

### ISSUE THREAD

**Issue by doidoit** [finset-io/better-qa#86]
- 화면 위치
: 내 자산 연결하기 - 약관 동의 [가입상품 목록 조회를 위해 동의가 필요해요] 2번째 페이지

- As is 
: [동의하고 계속 진행] 버튼을 누르면
[오류가 발생했습니다 다시 시도해주세요] 메시지가 뜸. 

- To be
: 정상적으로 다음 페이지 (000님, 네이버 인증서로 인증해주세요.)로 
연결될 수 있도록 해야 함.  

- 케이스1 **(권프로님)**

![Image](https://user-images.githubusercontent.com/98443099/179911473-37091e58-f59e-438d-9ac7-c6038b85a422.png)
![Image](https://user-images.githubusercontent.com/98443099/179911472-91c02294-6011-426e-90dd-bfeea44b5005.png)

**Comment by EtErNaLiFe12** [comment]
@doidoit  위와 같이 팝업이 뜨는 경우의 케이스는 backend로 POST 보낼 시 에러 발생때 나타나는 부분입니다. 현재는 재현 불가하므로 디버깅 불가하고 혹시나 계속 발생하고 계신 분이 있다면 말씀해주세요~ 일단 complete으로 돌리도록 하겠습니다.
